apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-kafka-app
  labels:
    app: hello-spring-kafka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-kafka-app
  template:
    metadata:
      labels:
        app: hello-spring-kafka-app
      # annotations:
      #   promtail.io/scrape: "true"         
      #   promtail.io/labels: "app=springboot"  
    spec:
      containers:
        - name: hello-spring-kafka-app
          # image: nazia141/hello-spring-boot-app:1.2
          image: nazia141/spring-kafka-app:1.2
          ports:
            - containerPort: 8080
          env:
            # - name: OTEL_SERVICE_NAME
            #   value: "springsvc"
            # - name: OTEL_TRACES_SAMPLER
            #   value: "always_on"
            # - name: OTEL_TRACES_EXPORTER
            #   value: "otlp"
            # - name: OTEL_METRICS_EXPORTER
            #   value: "otlp"
            # - name: OTEL_LOGS_EXPORTER
            #   value: "otlp"
            # - name: OTEL_EXPORTER_OTLP_PROTOCOL
            #   value: "grpc"
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "http://opentelemetry-collector-collector.opentelemetry.svc.cluster.local:4317"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: hello-spring-kafka-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  
  selector:
    app: hello-spring-kafka-app
